---
ID: "096eb689-0e2f-4263-90fa-79838fbc9aa8"
Parent: "4c9fbd5e-1e6c-4ce4-8c21-fa8ef73d2574"
Template: "4c9fbd5e-1e6c-4ce4-8c21-fa8ef73d2574"
Path: /sitecore/templates/Project/DemoNextjsTenant/JSS Settings/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230516T071140Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "466575e5-2786-49b0-abb3-5165bdc6c25d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230516T071140Z
