---
ID: "b4b28f4a-91a8-4c5c-a4ac-7bbb19a23a7a"
Parent: "41b904aa-6444-4f02-b6ce-f879f3e49bdd"
Template: "41b904aa-6444-4f02-b6ce-f879f3e49bdd"
Path: /sitecore/templates/Project/DemoNextjsTenant/Page/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {41B904AA-6444-4F02-B6CE-F879F3E49BDD}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230516T071139Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\admin
    - ID: "5d2f0e3e-56d8-48da-9b4f-6db350dd92a1"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e2954eb3-fcd4-411e-8ee2-4e6e2f1e98ef"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230516T071142Z
